// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

class Book {
  String kind;
  String id;
  String etag;
  String selfLink;
  VolumeInfo volumeInfo;
  SaleInfo saleInfo;
  AccessInfo accessInfo;
  bool isFavorite;

  Book({
    this.kind,
    this.id,
    this.etag,
    this.selfLink,
    this.volumeInfo,
    this.saleInfo,
    this.accessInfo,
    this.isFavorite = false,
  });
}

class AccessInfo {
  String country;
  String viewability;
  bool embeddable;
  bool publicDomain;
  String textToSpeechPermission;
  Epub epub;
  Pdf pdf;
  String accessViewStatus;

  AccessInfo({
    this.country,
    this.viewability,
    this.embeddable,
    this.publicDomain,
    this.textToSpeechPermission,
    this.epub,
    this.pdf,
    this.accessViewStatus,
  });
}

class Epub {
  bool isAvailable;
  String acsTokenLink;

  Epub({
    this.isAvailable,
    this.acsTokenLink,
  });
}

class Pdf {
  bool isAvailable;

  Pdf({
    this.isAvailable,
  });
}

class SaleInfo {
  String country;
  String saleability;
  bool isEbook;
  Price listPrice;
  Price retailPrice;
  String buyLink;

  SaleInfo({
    this.country,
    this.saleability,
    this.isEbook,
    this.listPrice,
    this.retailPrice,
    this.buyLink,
  });
}

class Price {
  double amount;
  String currencyCode;

  Price({
    this.amount,
    this.currencyCode,
  });
}

class VolumeInfo {
  String title;
  List<String> authors;
  String publisher;
  String publishedDate;
  String description;
  List<IndustryIdentifier> industryIdentifiers;
  int pageCount;
  Dimensions dimensions;
  String printType;
  String mainCategory;
  List<String> categories;
  double averageRating;
  int ratingsCount;
  String contentVersion;
  ImageLinks imageLinks;
  String language;
  String infoLink;
  String canonicalVolumeLink;

  VolumeInfo({
    this.title,
    this.authors,
    this.publisher,
    this.publishedDate,
    this.description,
    this.industryIdentifiers,
    this.pageCount,
    this.dimensions,
    this.printType,
    this.mainCategory,
    this.categories,
    this.averageRating,
    this.ratingsCount,
    this.contentVersion,
    this.imageLinks,
    this.language,
    this.infoLink,
    this.canonicalVolumeLink,
  });
}

class Dimensions {
  String height;
  String width;
  String thickness;

  Dimensions({
    this.height,
    this.width,
    this.thickness,
  });
}

class ImageLinks {
  String smallThumbnail;
  String thumbnail;
  String small;
  String medium;
  String large;
  String extraLarge;

  ImageLinks({
    this.smallThumbnail,
    this.thumbnail,
    this.small,
    this.medium,
    this.large,
    this.extraLarge,
  });
}

class IndustryIdentifier {
  String type;
  String identifier;

  IndustryIdentifier({
    this.type,
    this.identifier,
  });
}
