import 'enums/books.dart';

String imgUrl =
    'https://www.adobe.com/express/discover/ideas/media_1e0050318770e4a770caf5515f8120a3ea48c7c07.png?width=2000&format=webply&optimize=medium';

String des =
    'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.';

List<Map<String, Object>> exploreSections = [
  {
    'id': '1',
    'title': 'Genre 1',
    'size': BookItemSize.Normal,
    'view': ViewStyle.Horizontal,
    'books': [
      {
        'id': '1',
        'title': 'Title',
        'author': 'Author',
        'image': imgUrl,
        'description': des,
        'saved': false,
      },
      {
        'id': '2',
        'title': 'Title1',
        'author': 'Author',
        'image': imgUrl,
        'description': des,
        'saved': false,
      },
      {
        'id': '3',
        'title': 'Title2',
        'author': 'Author2',
        'image': imgUrl,
        'description': des,
        'saved': false,
      },
      {
        'id': '4',
        'title': 'Title3',
        'author': 'Author3',
        'image': imgUrl,
        'description': des,
        'saved': false,
      },
    ],
  },
  {
    'id': '2',
    'title': 'Genre 2',
    'size': BookItemSize.Normal,
    'view': ViewStyle.Horizontal,
    'books': [
      {
        'id': '1',
        'title': 'Title',
        'author': 'Author',
        'image': imgUrl,
        'description': des,
        'saved': false,
      },
      {
        'id': '2',
        'title': 'Title1',
        'author': 'Author',
        'image': imgUrl,
        'description': des,
        'saved': false,
      },
      {
        'id': '3',
        'title': 'Title2',
        'author': 'Author2',
        'image': imgUrl,
        'description': des,
        'saved': false,
      },
      {
        'id': '4',
        'title': 'Title3',
        'author': 'Author3',
        'image': imgUrl,
        'description': des,
        'saved': false,
      },
    ],
  },
  {
    'id': '3',
    'title': 'Genre 3',
    'size': BookItemSize.Normal,
    'view': ViewStyle.Horizontal,
    'books': [
      {
        'id': '1',
        'title': 'Title',
        'author': 'Author',
        'image': imgUrl,
        'description': des,
        'saved': false,
      },
      {
        'id': '2',
        'title': 'Title1',
        'author': 'Author',
        'image': imgUrl,
        'description': des,
        'saved': false,
      },
      {
        'id': '3',
        'title': 'Title2',
        'author': 'Author2',
        'image': imgUrl,
        'description': des,
        'saved': false,
      },
      {
        'id': '4',
        'title': 'Title3',
        'author': 'Author3',
        'image': imgUrl,
        'description': des,
        'saved': false,
      },
    ],
  },
  {
    'id': '4',
    'title': 'Genre 4',
    'size': BookItemSize.Normal,
    'view': ViewStyle.Horizontal,
    'books': [
      {
        'id': '1',
        'title': 'Title',
        'author': 'Author',
        'image': imgUrl,
        'description': des,
        'saved': false,
      },
      {
        'id': '2',
        'title': 'Title1',
        'author': 'Author',
        'image': imgUrl,
        'description': des,
        'saved': false,
      },
      {
        'id': '3',
        'title': 'Title2',
        'author': 'Author2',
        'image': imgUrl,
        'description': des,
        'saved': false,
      },
      {
        'id': '4',
        'title': 'Title3',
        'author': 'Author3',
        'image': imgUrl,
        'description': des,
        'saved': false,
      },
    ],
  },
  {
    'id': '5',
    'title': 'Genre 5',
    'size': BookItemSize.Normal,
    'view': ViewStyle.Horizontal,
    'books': [
      {
        'id': '1',
        'title': 'Title',
        'author': 'Author',
        'image': imgUrl,
        'description': des,
        'saved': false,
      },
      {
        'id': '2',
        'title': 'Title1',
        'author': 'Author',
        'image': imgUrl,
        'description': des,
        'saved': false,
      },
      {
        'id': '3',
        'title': 'Title2',
        'author': 'Author2',
        'image': imgUrl,
        'description': des,
        'saved': false,
      },
      {
        'id': '4',
        'title': 'Title3',
        'author': 'Author3',
        'image': imgUrl,
        'description': des,
        'saved': false,
      },
    ],
  },
  {
    'id': '6',
    'title': 'Genre 6',
    'size': BookItemSize.Normal,
    'view': ViewStyle.Horizontal,
    'books': [
      {
        'id': '1',
        'title': 'Title',
        'author': 'Author',
        'image': imgUrl,
        'description': des,
        'saved': false,
      },
      {
        'id': '2',
        'title': 'Title1',
        'author': 'Author',
        'image': imgUrl,
        'description': des,
        'saved': false,
      },
      {
        'id': '3',
        'title': 'Title2',
        'author': 'Author2',
        'image': imgUrl,
        'description': des,
        'saved': false,
      },
      {
        'id': '4',
        'title': 'Title3',
        'author': 'Author3',
        'image': imgUrl,
        'description': des,
        'saved': false,
      },
    ],
  },
];
